<?xml version="1.0" encoding="UTF-8"?>
<job releaseVersion="1.0" description="" log="./" lst="./" mnf="./">
  <tasks>
    <task path="../Programs/autoexec.sas" />
    <task path="../Programs/d0_dm.sas" />
  </tasks>
  <taskSpecs>
    <inputSpec path="../Programs/autoexec.sas" type="FILE" version="*" includeSubFolders="false" />
    <inputSpec path="../Programs/d0_dm.sas" type="FILE" version="*" includeSubFolders="false" />
  </taskSpecs>
  <otherSpecs>
    <inputSpec path="/Clinical Development/B_POC/Indication_001/Protocol_001/Study_001/Macros/mstudydy.sas" type="FILE" version="" includeSubFolders="false" />
    <inputSpec path="/Clinical Development/B_POC/Indication_001/Protocol_001/Study_001/RawData/dm.sas7bdat" type="FILE" version="" includeSubFolders="false" />
    <inputSpec path="/Clinical Development/B_POC/Indication_001/Protocol_001/Study_001/RawData/sda.sas7bdat" type="FILE" version="" includeSubFolders="false" />
    <inputSpec path="/Clinical Development/B_POC/Indication_001/Protocol_001/Study_001/RawData/ds.sas7bdat" type="FILE" version="" includeSubFolders="false" />
    <inputSpec path="/Clinical Development/B_POC/Indication_001/Protocol_001/Study_001/RawData/oe.sas7bdat" type="FILE" version="" includeSubFolders="false" />
    <inputSpec path="/Clinical Development/B_POC/Indication_001/Protocol_001/Study_001/RawData/spc.sas7bdat" type="FILE" version="" includeSubFolders="false" />
    <inputSpec path="/Clinical Development/B_POC/Indication_001/Protocol_001/Study_001/RawData/vs.sas7bdat" type="FILE" version="" includeSubFolders="false" />
  </otherSpecs>
  <outputPaths />
  <outputSpec enableVersioningForNewFiles="false">
    <versionType type="MAJOR" />
  </outputSpec>
  <parameters />
</job>

